services:
  - type: web
    name: newtxt-bot
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.main
    repo: https://github.com/Anilgurjar0008/newtxt
    branch: main
    autoDeploy: false
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 8000
