services:
  - type: web
    name: newtxt-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m src.main"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
